# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    curl -O https://download.clojure.org/install/linux-install-1.10.1.469.sh
    chmod +x linux-install-1.10.1.469.sh
    sudo ./linux-install-1.10.1.469.sh
  displayName: 'Install Clojure CLI'

- script: bash ./script/test
  displayName: 'Run tests script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
